### ISSUE TITLE
Create License

### ISSUE THREAD

**Issue by darvelo** [rr-/dotfiles#10]
Hey, @rr-. I'm trying to separate out the bspwm panel into its own repo to track my own changes, but before I do that I need to know what license the code is under. GPLv2, MIT, and BSD are all popular, and WTFPL is gaining popularity (and hilarity). Would you be able to choose a license and place a `LICENSE` file with the contents of that license into the root or `mod-bswpm` dir sometime soon?

**Comment by rr-** [comment]
Sure. While I like GPL for its open source spirit, I don't think it makes much sense here. What do you think of MIT?

**Comment by darvelo** [comment]
Sure, most of my projects are MIT. I'm a fan of GPL too, but I realize not everyone is.

**Comment by rr-** [comment]
Resolved in c3e411a171753eb5266b481e6cb7e46f54475028.

**Comment by darvelo** [comment]
Thanks!
